name = "PicoQuantTTTR"
uuid = "dd5abcca-2177-4979-a5ef-16b2ccc21404"
authors = ["Hugo Levy-Falk <klafyvel@klafyvel.me> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
